### ISSUE TITLE
CRC doesn't match. File is corrupted.

### ISSUE THREAD

**Issue by rei-vilo** [ArduCAM/ArduCAM_ESP8266_UNO#1]
### Basic Infos

Updating ArduCAM_ESP8266_UNO from Arduino 1.6.9 Boards Manager
#### Hardware

ArduCAM ESP8266 UNO board
### Description

Error message

> CRC doesn't match. File is corrupted.
### Settings in IDE

Arduino IDE 1.6.9
Mac OS X 10.11.5
### Sketch

None
### Debug Messages

None

<img width="400" alt="capture 2016-06-13 a 15 06 17" src="https://cloud.githubusercontent.com/assets/951776/16008519/bb01a73c-3178-11e6-9424-8b0a42bc448b.png">

**Comment by ArduCAM** [comment]
@Rei Vilo, it is the know issue.
You have to remove the packages already downloaded in the Arduino15 folder, which is located in C:\Users\XXX\AppData\Local\Arduino15 windows system.
Not sure where it is in Mac.

**Comment by rei-vilo** [comment]
Thank you for the tip. 

I deleted `~/Library/Arduino15/staging/packages/ArduCAM_ESP8266_UNO.zip` and installation went fine.

Surprisignly, this issue does"t arise for other platforms on Arduino 1.6.9.
